base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("employees.urls")),
]

employees/urls.py
from django.urls import path

from employees.views import employee_hierarchy, get_next_level_employees, employee_list

urlpatterns = [
    path("", employee_hierarchy, name="employee_hierarchy"),
    path(
        "get_next_level/<int:supervisor_id>/",
        get_next_level_employees,
        name="get_next_level",
    ),
    path("employee_list/", employee_list, name="employee_list"),
]

employees/models.py
from django.db import models


class Employee(models.Model):
    full_name = models.CharField(max_length=255)
    position = models.CharField(max_length=100)
    hire_date = models.DateField()
    email = models.EmailField()
    supervisor = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.full_name

employees/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from .models import Employee


def is_ajax(request):
    return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


def employee_hierarchy(request):
    employees = Employee.objects.filter(supervisor=None)
    return render(
        request, "employees/employee_hierarchy.html", {"employees": employees}
    )


def get_next_level_employees(request, supervisor_id):
    employees = Employee.objects.filter(supervisor=supervisor_id).values(
        "id", "full_name", "position", "email"
    )
    return render(request, "employees/employee_tree.html", {"employees": employees})


def employee_list(request):
    employees = Employee.objects.all()

    # Sorting logic
    sort_field = request.GET.get("sort_field", "full_name")
    employees = employees.order_by(sort_field)

    # Searching logic
    search_query = request.GET.get("search_query", "")
    if search_query:
        employees = employees.filter(
            full_name__icontains=search_query,
            position__icontains=search_query,
            email__icontains=search_query,
        )

        # Check if it's an Ajax request
    if is_ajax(request=request):
        html_context = {
            "html": render_to_string(
                "employees/employee_list_ajax.html", {"employees": employees}, request
            )
        }
        return JsonResponse(html_context)
    context = {"employees": employees}
    return render(request, "employees/employees_list.html", context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Employee Hierarchy Application</title>
    <!-- Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
    <!-- Bootstrap JS and jQuery scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Employee Hierarchy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'employee_hierarchy' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'employee_list' %}">Employee List</a>
            </li>
        </ul>
    </div>
</nav>


<div class="container mt-3">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/employees/employee_hierarchy.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

{% block content %}
<div id="employee-tree">
    <ul id="tree" class="tree">
        {% for employee in employees %}
            <li emp_id="{{ employee.id }}">
                <i class="indicator glyphicon glyphicon-minus-sign"></i>
                {{ employee.full_name }} ({{ employee.position }}) - {{ employee.email }}
                    <ul>
                        {% for employee_inner in employee.employee_set.all %}
                            <li emp_id="{{ employee_inner.id }}">
                                <i class="indicator glyphicon glyphicon-plus-sign"></i>
                                {{ employee_inner.full_name }} ({{ employee_inner.position }}) - {{ employee_inner.email }}
                            </li>
                        {% endfor %}
                    </ul>
            </li>
        {% endfor %}
    </ul>
</div>
<script>
    const url = window.location.href + "{% url 'get_next_level' supervisor_id=0 %}".slice(1, -3);
    console.log(url);
</script>
<script src="{% static 'js/hierarchy_logic.js' %}"></script>
{% endblock %}

templates/employees/employee_list_ajax.html
{% for employee in employees %}
    <tr>
      <td>{{ employee.full_name }}</td>
      <td>{{ employee.position }}</td>
      <td>{{ employee.email }}</td>
      <td>{{ employee.hire_date }}</td>
      <td>{{ employee.supervisor }}</td>
    </tr>
{% endfor %}

templates/employees/employee_tree.html
<ul>
    {% for employee in employees %}
        <li class="branch" emp_id="{{ employee.id }}">
            <i class="indicator glyphicon glyphicon-plus-sign"></i>
            {{ employee.full_name }} ({{ employee.position }}) - {{ employee.email }}
        </li>
    {% endfor %}
</ul>

templates/employees/employees_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>Employee List</h2>
  <form method="get" id="filter-form" action="{% url 'employee_list' %}">
      <div class="row">
          <div class="col-6">
            <label for="sort_field" class="form-label">Sort by:</label>
            <select class="form-select" name="sort_field" id="sort_field">
              <option value="full_name">Full Name</option>
              <option value="position">Position</option>
              <option value="email">Email</option>
              <option value="hire_date">Hire date</option>
            </select>
          </div>
          <div class="col-6">
              <label for="sort_field" class="form-label">Search by:</label>
              <input type="text" class="form-control" name="search_query" id="search_query" placeholder="Search:">
          </div>
          <div class="row-6 my-4">
              <button type="submit" class="w-100 btn btn-primary btn-lg">Process</button>
          </div>
      </div>
  </form>

  <table id="employee-table">
    <thead>
      <tr>
        <th>Full Name</th>
        <th>Position</th>
        <th>Email</th>
        <th>Hire Date</th>
        <th>Supervisor</th>
      </tr>
    </thead>
    <tbody>
      {% include 'employees/employee_list_ajax.html' %}
    </tbody>
  </table>
  <script src="{% static 'js/emp_list_filtering.js' %}"></script>
{% endblock %}